swagger: "2.0"
info:
  description: "API criada para fornecer as mais diversas soluções para o mercado de pagamentos (eCommerce, mCommerce)."
  version: "1.0.0"
  title: "API Pagamentos"
  license:
    name: "ISC"
host: "awsapi.com"
basePath: "/v1"
tags:
- name: "pagamento"
  description: "Pagamento API"
schemes:
- "https"
- "http"
paths:
  /pagamento/antifraud:
    post:
      tags:
      - "validação"
      - "antifraud"
      summary: "Retorna o token de validação."
      description: "Serviço de antifraude para validação de dados do pagamento."
      operationId: "antifraud"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "authorization"
        in: "header"
        description: "Token de acesso obtido no endpoint de autenticação."
        required: true
        type: "string"
      - name: "cartaoNumero"
        in: "formData"
        description: "Número do cartão de crédito sem a informação CVV."
        required: true
        type: "string"
      - name: "clienteId"
        in: "formData"
        description: "ID do cliente da plataforma."
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Validação realizada com sucesso."
        400:
          description: "Requisição inválida."
        401:
          description: "Autenticação inválida."
        404:
          description: "Não encontrada."
        500:
          description: "Erro interno do servidor ou serviço."
      security:
      - pagamentostore_auth:
        - "write:pagamentos"
        - "read:pagamentos"
  /pagamento:id:
    get:
      tags:
      - "pagamento"
      - "informacoes"
      - "status"
      summary: "Retorna o pagamento."
      description: "Identifica o pagamento pelo seu ID."
      operationId: "getPagamento"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "Operação realizada com sucesso"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/pagamento"
        401:
          description: "Autenticação inválida."
        404:
          description: "Não encontrada."
        500:
          description: "Erro interno do servidor ou serviço."
      security:
      - petstore_auth:
        - "write:pagamentos"
        - "read:pagamentos"
    post:
      tags:
      - "pagamento"
      summary: "Adiciona pagamento a compra"
      description: "Realiza o pagamento através de cartão de crédito"
      operationId: "addPagamentoCredito"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "authorization"
        in: "header"
        description: "Token de acesso obtido no endpoint de autenticação."
        required: true
        type: "string"
      - name: "antifraud"
        in: "header"
        description: "Token com a validação da forma de pagamento."
        required: true
        type: "string"
      - name: "parcelas"
        in: "formData"
        description: "Quantidade de parcelas do pagamento."
        required: false
        type: "integer"
        format: "int64"
      - name: "pagamento"
        in: "formData"
        description: "Informações sobre o pagamento."
        required: true
        schema:
          $ref: "#/definitions/Pagamento"
      responses:
        200:
          description: "Pagamento realizado com sucesso."
        400:
          description: "Requisição inválida."
        401:
          description: "Autenticação inválida."
        402:
          description: "Requisição válida, mas pagamento inválido."
        404:
          description: "Não encontrado."
        500:
          description: "Erro interno do servidor ou serviço."
      security:
      - pagamentostore_auth:
        - "write:pagamentos"
        - "read:pagamentos"
securityDefinitions:
  pagamentostore_auth:
    type: "oauth2"
    authorizationUrl: "http://pagamentostore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pagamentos: "Persiste o pagamento"
      read:pagamentos: "Ler o pagamento"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Pagamento:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      usuario:
        $ref: "#/definitions/Usuario"
      moeda:
        type: "string"
      valor:
        type: "string"
      frete:
        type: "string"
      status:
        type: "string"
        description: "Tipo"
        enum:
        - "credito"
        - "debito"
        - "boleto"
    xml:
      name: "Pagamento"
  Usuario:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      cpf:
        type: "string"
      nome:
        type: "string"
      endereco:
        type: "string"
    xml:
      name: "Usuario"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
