swagger: '2.0'
info:
  description: Este é um exemplo de serviço de validação de pagamentos
  version: 1.0.0
  title: API Pagamentos
  license:
    name: ISC
host: payment.aws.com
basePath: /v2
tags:
- name: payment
  description: URL's de acesso interno
- name: validation
  description: URL's de acesso para serviços de terceiros
schemes:
- https

paths:
  # Registra compra
  /buy/{method}:
    post:
      tags:
      - payment
      summary: Registrar Pedido
      description: Registra pedido de pagamento iniciando processo de compra
      operationId: setPagamento
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: authorization
        in: header
        description: Token de acesso obtido no endpoint de autenticação
        required: true
        type: string
      # Typo de pagamento no metodo
      - name: method
        in: path
        description: Typo de pagamento, visa, boleto, mastercard, etc
        required: true
        type: string
        format: varchar
      # Nome Sobrenome, CPF, Completo, Endereço, CEP, Valor da compra, Valor do frete, todos campos obrigatorios
      - in: body
        name: name
        description: Nome Sobrenome do comprador
        required: true
        type: string
        format: varchar
      - in: body
        name: taxid
        description: CPF ou CNPJ somente digitos
        required: true
        type: number
        format: varchar
      - in: body
        name: address
        description: ESstado, Cidade, Rua, numero, Complemento Separados por virgula
        required: true
        type: string
        format: varchar
      - in: body
        name: cep
        description: CEP só numeros
        required: true
        type: number
        format: varchar
      - in: body
        name: value
        description: Valor da compra
        required: true
        type: float
        format: float
      - in: body
        name: fret
        description: Valor do frete
        required: true
        type: float
        format: float
      - in: body
        name: description
        description: Informações sobre o pagamento
        required: true
        format: varchar

      # Pagamento
      - in: body
        name: installments
        description: Quantidade de parcelas do pagamento
        required: false
        type: integer
        format: int16
      - in: body
        name: cc
        description: 4 digitos do cartao de credito para validar antifraude
        required: false
        type: integer
        format: int16
      responses:
        201:
          description: Ordem criada com sucesso
        400:
          description: Requisição inválida
        401:
          description: Chave de autenticação inválida
        405:
          description: Entrada invalida
        408:
          description: Tempo esgotado
        429:
          description: Pedidos em excesso da mesma fonte
        500:
          description: Erro interno do servidor ou serviço
        503:
          description: Serviço Indisponivel
      security:
      - petstore_auth:
        - write:payment
        - read:payment
  
  /buy/{id}:
    # Checa status da compra
    get:
      tags:
      - payment
      summary: Retorna o status do pagamento
      description: Identifica o pagamento pelo seu ID
      operationId: getPagamento
      produces:
      - application/json
      parameters:
      - name: authorization
        in: header
        description: Token de acesso obtido no endpoint de autenticação
        required: true
        type: string
      # Typo de pagamento no metodo
      - name: id
        in: path
        description: Identificador da compra
        required: true
        type: number
        format: int64
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
            type: object
            items:
              $ref: #/definitions/pagamento
        401:
          description: Autenticação inválida
        404:
          description: Não encontrada
        405:
          description: Entrada invalida
        408:
          description: Tempo esgotado
        429:
          description: Pedidos em excesso da mesma fonte
        500:
          description: Erro interno do servidor ou serviço
        503:
          description: Serviço Indisponivel
      security:
      - petstore_auth:
        - write:payment
        - read:payment

  /billet/{id}:
    # Mostra o boleto para pagamento
    get:
      tags:
      - payment
      summary: Gera boleto
      description: Mostra o boleto para pagamento
      operationId: getBillet
      produces:
      - text/html; charset=utf-8
      parameters:
      - name: id
        in: path
        description: Identificador da compra
        required: true
        type: number
        format: int64
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
            type: object
            items:
              $ref: #/definitions/pagamento
        401:
          description: Autenticação inválida
        404:
          description: Não encontrada
        405:
          description: Entrada invalida
        408:
          description: Tempo esgotado
        429:
          description: Pedidos em excesso da mesma fonte
        500:
          description: Erro interno do servidor ou serviço
        503:
          description: Serviço Indisponivel
      security:
      - petstore_auth:
        - write:payment
        - read:payment


  # Anti fraude
  /validation/antifraud/{id}:
    post:
      tags:
      - validation
      summary: Retorno do antifaude
      description: Retorno do serviço de antifraude para validação de dados do pagamento
      operationId: antifraud
      consumes:
      - application/json
      parameters:
      - name: authorization
        in: header
        description: Token de acesso obtido no endpoint de autenticação
        required: true
        type: string
      - name: id
        in: path
        description: Identificador da compra
        required: true
        type: number
        format: int64
      - name: code
        in: body
        description: Codigo retornado da autorização da compra
        required: true
        type: string
        format: varchar
      responses:
        201:
          description: Objeto criado com sucesso
        400:
          description: Requisição inválida
        401:
          description: Chave de autenticação inválida
        405:
          description: Entrada invalida
        408:
          description: Tempo esgotado
        500:
          description: Erro interno do servidor ou serviço
        503:
          description: Serviço Indisponivel
      security:
      - pagamentostore_auth:
        - write:pagamentos
        - read:pagamentos

  # Validação do pagamento
  /validation/payment/:id:
    post:
      tags:
      - validation
      summary: Pagamento Aprovado
      description: Recebe do serviço do banco informação que o valor foi pago pelo cartão ou o boleto foi pago
      operationId: complete
      consumes:
      - application/json
      parameters:
      - name: authorization
        in: header
        description: Token de acesso obtido no endpoint de autenticação
        required: true
        type: string
      - name: id
        in: path
        description: Identificador da compra
        required: true
        type: number
        format: int64
      - name: code
        in: body
        description: Codigo retornado da autorização da compra
        required: true
        type: string
        format: varchar
      responses:
        201:
          description: Objeto criado com sucesso
        400:
          description: Requisição inválida
        401:
          description: Chave de autenticação inválida
        405:
          description: Entrada invalida
        408:
          description: Tempo esgotado
        500:
          description: Erro interno do servidor ou serviço
        503:
          description: Serviço Indisponivel
      security:
      - pagamentostore_auth:
        - write:pagamentos
        - read:pagamentos


    




# Segurança a definir
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: http://petstore.swagger.io/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Order:
    type: object
    properties:
      id:
        type: integer
        format: int64
      petId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
        enum:
        - placed
        - approved
        - delivered
      complete:
        type: boolean
        default: false
    xml:
      name: Order
  Category:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Category
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status
    xml:
      name: User
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Tag
  Pet:
    type: object
    required:
    - name
    - photoUrls
    properties:
      id:
        type: integer
        format: int64
      category:
        $ref: #/definitions/Category
      name:
        type: string
        example: doggie
      photoUrls:
        type: array
        xml:
          name: photoUrl
          wrapped: true
        items:
          type: string
      tags:
        type: array
        xml:
          name: tag
          wrapped: true
        items:
          $ref: #/definitions/Tag
      status:
        type: string
        description: pet status in the store
        enum:
        - available
        - pending
        - sold
    xml:
      name: Pet
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io